blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
blog_show:
    path:     /Details/{id}
    defaults: { _controller: BlogBundle:Default:show }
recherche_blog:
    path:     /searchblog
    defaults: { _controller: BlogBundle:Default:RechercheBlog }
new_blog:
    path:     /newblog
    defaults: { _controller: BlogBundle:Default:new }