<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxnq6ii\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxnq6ii/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRxnq6ii.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRxnq6ii\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRxnq6ii\appDevDebugProjectContainer([
    'container.build_hash' => 'Rxnq6ii',
    'container.build_id' => '0e16c53b',
    'container.build_time' => 1582714845,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxnq6ii');
