<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJxmcvbd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxmcvbd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJxmcvbd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJxmcvbd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJxmcvbd\appDevDebugProjectContainer([
    'container.build_hash' => 'Jxmcvbd',
    'container.build_id' => '2b56385d',
    'container.build_time' => 1582638847,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxmcvbd');
